version: '2'
services:
  web:
    build: .
    ports:
     - "8080:80"
    volumes:
     - ./Lychee/:/var/www/html
    environment:
      APACHE_RUN_GROUP: webu
      APACHE_RUN_USER: webu

  mysql-server:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password